### ISSUE TITLE
需求: 能提供一种上下面板的方式吗?

### ISSUE THREAD

**Issue by leeyaunlong** [Misuzu2027/syplugin-dual-doc-list#2]
需求: 能提供一种上下面板的方式吗?
现在左右显示父子关系, 能提供上下面板显示父子关系的方式吗?

**Comment by Misuzu2027** [comment]
不考虑了弄了。感觉比较小众，我个人也用不上，此前用过印象笔记、为知笔记、Joplin 等三栏式布局的笔记软件，没咋见过上下布局的 😂

**Comment by Misuzu2027** [comment]
v0.0.8 支持 二级文档列表Dock，可以开启后把 Dock 拖到文档树下方显示，就可以上下显示。

不过我个人体验了一下，因为二级文档列表头部挺多功能，展示起来不太清爽，可以如果不需要这些功能，可以自定义CSS隐藏不需要的功能，我这里提供一个全部隐藏的作为参考。

```css
/* 隐藏二级文档列表头部功能 */
.misuzu2027__doc-list .flat_doc_tree--top{
   display : none;
}
```
