### ISSUE TITLE
二级文档树：一些希望增加的功能设计

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#3]
1. 文档可以在二级文档树定位吗？现在使用“文档的定位功能”，文档只能在一级文档树定位， 有时候有些文档是通过文本中的块链接反向定位的，在这种反向定位的操作之下，只在一级文档树里面定位，因为一级文档树很长，那么这种反向定位后，文档的“移动”还是非常麻烦，还是只能和之前用文档标题的那三个点操作——二级文档树这时候基本只能起到一个“查看”的作用。
2. 二级文档书的气泡可以关掉吗？参考链滴这篇帖子[文档气泡](https://ld246.com/article/1700237659585)，这个随着鼠标飞舞的气泡着实有点干扰。
3. 希望一级文档树可以保持折叠状态，即点击folder时，子page只在二级文档树展开。如果不是这样的话，那么两个文档层级同时展开，界面十分繁杂，而且也不便于二级到一级的拖动。
ps：我目前的使用体验世——如果1、3两点做不到的话，现在的二级文档树多少有点……鸡肋（本来很需要二级文档树的，现在的二级文档树对一级没有太多辅助作用，很多操作，有无二级文档树的体验效果居然差不多……）

**Comment by luluciamk** [comment]
又又ps，在另一个issue里看到大大说过印象笔记——没错，基本的二级文档树如果能做到印象笔记那种二级文档树设计，这才能达到可用状态，供参考。 
很难得才能登上github，所以还要补充一点。
现在使用时，发现要切换展开不同文件夹的文档的话，操作时“双击”鼠标左键，这个操作总感觉有点不顺手。
可能思源本身有限制，不能做到印象笔记那种，单击父级而在二级文档树展开子级
那么可否将这个切换展开，双击鼠标左键的动作，改变成按住某个键（ctrl或者alt之类的）来辅助切换。
这么建议的原因是——
切换一次，也许只需要点两下鼠标。
如果在某个场景下需要频繁切换，那么这时候鼠标点击的数量就是翻倍增加，操作动作都会变成双倍，加大了操作量（累）

**Comment by Misuzu2027** [comment]
1. 二级文档列表定位可以增加，不过为了防止二级文档列表不存在定位的文档，定位时会把二级文档列表的路径切换到定位文档的所在路径。
2. 气泡这个主要是为了跟思源默认文档树保持一致，可以通过 CSS 代码片段进行隐藏。
3. 这里不太明白，目前思源的笔记本默认单击“展开/折叠”；文档需要点击箭头才能"展开/折叠"。我也觉得有时候单击切换笔记本路径的时候，笔记本"展开/折叠"很麻烦，所以增加了“双击展开笔记本”的设置，开启后还是可以通过单击箭头切换笔记本的"展开/折叠"。所以目前操作还是比较明确的：一级文档树的“展开/折叠”点击左侧箭头，切换二级文档列表路径就单击 笔记本/文档名部分。

ps：目前是切换二级文档列表路径是单击 笔记本/文档 的，点两次才切换可能是其他插件导致的。
不方便上 github 可以在 思源爱好者折腾群（1017854502）找我。

第二点 隐藏二级文档列表中文档的引用数量的 css 片段：
```css
div[data-misuzu2027-embed-dualdoclist] .popover__block.counter.b3-tooltips.b3-tooltips__nw{
  display:none;
}
```

**Comment by luluciamk** [comment]
感谢回复。
2气泡问题顺利解决。
3关于折叠展开问题，应该是和我另一个插件产生冲突，经提醒也得到解决。😘

1 文档的定位问题，这里详细描述一下，供大大设计时参考。（说得比较啰嗦）

现在的问题是——
点开某个文本，在文本中用快捷键命令，“定位这个文档在文档树中的位置”，这时候，定位会在一级文档树打开，同时这个文档的所有同级文档也会全部排列出来。

所说的，“文档在二级文档树定位”，即用快捷键操作时，希望定位只出现在“二级文档树”，一级文档树的界面保持尽量折叠状态。（即只展现父级，不要再在一级文档树中展开子级）

另，今天测试时，又发现另一个小问题（之前因为气泡问题都没怎么好好用过二级文档树啊哈哈）
即，**在二级文档树中选中某个文档点开，这个文档在二级文档树中的位置没有任何标识色**——一般这种被打开的文档，在文档树中应该有“高亮”背景色之类，意即“它是被选中的”，通过这种高亮色和其他文档区分开来，使人可以一目了然看清这个文档现在在文档树中的位置。

我用的是原生midnight主题，特意换了别的主题尝试，发现这应该不是主题问题。

**Comment by Misuzu2027** [comment]
二级文档列表的定位不会操作一级文档树。效果如视频所示：


https://github.com/user-attachments/assets/e04b94a5-c469-4305-8141-f0f2d15d8997


二级文档列表点击文档后没有标识算是一个bug，这个版本修复。

**Comment by luluciamk** [comment]
感谢大大更新，今天使用时又产生一点新的想法。（可能是个比较大的能力挑战-在思源架构内）
即——大大难道没有觉得现在二级文档树的显示逻辑有点奇怪吗？
如图
![捕获](https://github.com/user-attachments/assets/ce8c72a2-a129-442c-89ba-43481b3b77e7)

## 1参考印象笔记这种传统笔记树
那么二级文档树中就不该出现“文件夹”（参考黄色标记）
如此就能确保，每在一级树中点开文件夹，其对应的二级就是绝对的单层文档。

现在这个版本的二级树设计，则是点开一级树的父级后，二级里面依旧是文件夹和文件混合出现。
 
在这两种逻辑中，我个人更倾向印象笔记的这种显示逻辑。
在印象版的逻辑下，可以确保单文档具有隐形维度的高等级，即单文档的层级高于文件夹。
文档比文件夹要灵活许多，在这种逻辑下，不管是文档的管理，还是笔记的记录，都比现在这种【思源的文档和文件夹混合显示】要高效便利。

一级文档树显示文件夹和文档，二级文档树继续显示文件夹和文档的话，两者界面高度重合，这会导致

1信息上有点混乱重合

- **一级文档树展开状态下**，两者界面相同，二级树的意义只在于“拖动”，信息重合造成繁冗，

- **一级文档树折叠状态下**，文件夹和文件混合排布，文件夹的信息价值不是很大

现在可以设置“展开子文档”，就能取代这个子级folder。
子级folder这种低价值信息数量多且散落在二级树中，这只增加了二级树的信息混乱， 还拉长了文档树——这种位置实则是寸土寸金啊。

2操作时也经常会造成混乱

- 究竟是a在一级文档树的父folder里再点开子folder呢？还是b直接在二级文档树点开子folder呢？

- 如果是b，点开之后又没有什么便利的返回上级动作，还是得回到一级树重新点开所有的子folder。

- 如果将一级树和二级树的文档文件夹加以区分，那么在操作上对使用者也可以加以引导，可以减少相当量的繁琐操作。

综上，我认为印象笔记-joplin-onenote-有道云，这种传统的二级文档树显示逻辑，比较好用。

当然，这种设计可能比较有挑战性。

## 那么，我的第二个想法是——**这个二级文档树可否增加对“折叠文件夹”的标识？**
毕竟现在如图所示，二级文档树中的文件夹和文档看起来没什么区别。
我现在是用emoji来区分两者
但我又觉得emoji花里胡哨，实际上不怎么喜欢，于是经常忘记添加，于是导致如果只看一级inbox的折叠态时，在二级文档树里经常无法区分文件夹和文档。
参考蓝色所示，可否增加一点什么标识（文件夹的字体加粗之类的？）

**Comment by Misuzu2027** [comment]
1. 思源没有文件夹类型，只有文档类型，所以照搬印象笔记等有文件夹（笔记本）等软件的逻辑是行不通的。
2. 标识目前没有好的实现样式想法，因为需要适配不同主题，就劲量跟官方的样式一致。不过用户可以通过自定义CSS来标识。在没使用数据库查询的情况下（有空我向官方提一个issue，提供一个批量查询文档信息的接口，这样数据库查询也可以获取到子文档数量了），每一个文档标题有一个 data-count 属性，用来表示这个文档子文档的数量，可以根据这个属性不等于0来隐藏该文档或给这个文档添加背景色。

下面给一些参考的 CSS ，按需取用：
```css
/* 隐藏二级文档列表含有子文档的文档 */
.misuzu2027__doc-list li[data-type="navigation-file"][data-count]:not([data-count="0"]){
    display:none;
}
/* 隐藏文档树不含子文档的文档 */
.file-tree.sy__file li[data-type="navigation-file"][data-count][data-count="0"]{
    display:none;
}
/* 添加二级文档列表含有子文档的文档背景色 */
.misuzu2027__doc-list li[data-type="navigation-file"][data-count]:not([data-count="0"]){
    background-color: #e0f7fa;
}
```

**Comment by luluciamk** [comment]
感谢，大大给的三个css基本可以解决问题。❤

**Comment by luluciamk** [comment]
大大。更新最新版本0.7后，右键失灵，失去弹窗，无法在二级文档树进行文档操作了。

**Comment by Misuzu2027** [comment]
早上的 0.0.8 修复了这个问题，如果集市没有显示更新，需要重启思源

**Comment by luluciamk** [comment]
市场里的最新版本是0.0.7，是不是还没更新。

**Comment by Misuzu2027** [comment]
跟隔壁插件版本搞混了  😂，0.0.7确实修复了，不过更新插件可能没有重新加载，所以重启思源就好了。

发现整个文档标题添加背景色有点突兀，弄了个只在开头的icon显示背景的css：

```css
/* 含有子文档的 icon 背景 */
.misuzu2027__doc-list li[data-type="navigation-file"][data-count]:not([data-count="0"]) span:first-of-type{
  background-image: linear-gradient(to top, #a8edea 0%, #fed6e3 100%);
}
```
